### ISSUE TITLE
Cannot set BLE_KEEP_ACTIVE on HERO 7

### ISSUE THREAD

**Issue by Natureshadow** [gopro/OpenGoPro#112]
**Component**
What is the bug in? 
- Demos (python sdk, etc)

**Describe the bug**

```plain
INFO     12:01:29.539 <----------- register_value_update : StatusId.ENCODING                                                       builders.py:67
INFO     12:01:29.622 -----------> {                                                                                               builders.py:69
             "status": "SUCCESS",                                                                                                                
             "id": "UUID.CQ_QUERY_RESP::QueryCmdId.REG_STATUS_VAL_UPDATE",                                                                       
             "StatusId.ENCODING": false                                                                                                          
         }                                                                                                                                       
INFO     12:01:29.634 <----------- register_value_update : StatusId.SYSTEM_READY                                                   builders.py:67
INFO     12:01:29.708 -----------> {                                                                                               builders.py:69
             "status": "SUCCESS",                                                                                                                
             "id": "UUID.CQ_QUERY_RESP::QueryCmdId.REG_STATUS_VAL_UPDATE",                                                                       
             "StatusId.SYSTEM_READY": true                                                                                                       
         }                                                                                                                                       
INFO     12:01:29.719 <----------- Set LED: LED.BLE_KEEP_ALIVE                                                                    builders.py:476
INFO     12:01:29.719 BLE is ready!                                                                                                  gopro.py:466
INFO     12:01:29.733 <----------- GET_THIRD_PARTY_API_VERSION                                                                    builders.py:242
WARNING  12:01:29.800 Received non-success status: ErrorCode.ERROR                                                                   gopro.py:613
INFO     12:01:29.808 ----------->                                                                                                builders.py:487
         {                                                                                                                                       
             "status": "ERROR",                                                                                                                  
             "id": "UUID.CQ_SETTINGS_RESP::SettingId.LED"                                                                                        
         }                                                                                                                                       
INFO     12:01:29.820 <----------- Set LED: LED.BLE_KEEP_ALIVE                                                                    builders.py:476
ERROR:root:A message handler raised an exception: Error in path (parsing)
stream read less than specified amount, expected 1, found 0.
Traceback (most recent call last):
  File "/tmp/gpfoo/lib/python3.9/site-packages/dbus_next/message_bus.py", line 668, in _process_message
    result = handler(msg)
  File "/tmp/gpfoo/lib/python3.9/site-packages/bleak/backends/bluezdbus/client.py", line 1079, in _parse_msg
    self._notification_callbacks[message.path](
  File "/tmp/gpfoo/lib/python3.9/site-packages/open_gopro/gopro.py", line 491, in _notification_handler
    response._parse()
  File "/tmp/gpfoo/lib/python3.9/site-packages/open_gopro/responses.py", line 512, in _parse
    self.data = self._parsers[self.id].parse(buf)  # type: ignore
  File "/tmp/gpfoo/lib/python3.9/site-packages/construct/core.py", line 288, in parse
    return self.parse_stream(io.BytesIO(data), **contextkw)
  File "/tmp/gpfoo/lib/python3.9/site-packages/construct/core.py", line 300, in parse_stream
    return self._parsereport(stream, context, "(parsing)")
  File "/tmp/gpfoo/lib/python3.9/site-packages/construct/core.py", line 312, in _parsereport
    obj = self._parse(stream, context, path)
  File "/tmp/gpfoo/lib/python3.9/site-packages/construct/core.py", line 2120, in _parse
    subobj = sc._parsereport(stream, context, path)
  File "/tmp/gpfoo/lib/python3.9/site-packages/construct/core.py", line 312, in _parsereport
    obj = self._parse(stream, context, path)
  File "/tmp/gpfoo/lib/python3.9/site-packages/construct/core.py", line 4101, in _parse
    stream_read(stream, pad, path)
  File "/tmp/gpfoo/lib/python3.9/site-packages/construct/core.py", line 91, in stream_read
    raise StreamError("stream read less than specified amount, expected %d, found %d" % (length, len(data)), path=path)
construct.core.StreamError: Error in path (parsing)
stream read less than specified amount, expected 1, found 0
```

**To Reproduce**

`gopro-demo`

**Hardware**
- Camera: Hero7
- Desktop: KDE

**Comment by Natureshadow** [comment]
Ah, the HERO 7 just does not speak the OpenGopro protocol. My fault!
