### ISSUE TITLE
403 Client Error when try to use setting commands via USB

### ISSUE THREAD

**Issue by GrayMask** [gopro/OpenGoPro#364]
I am trying to set GoPro via USB using follow python scripts:
```
import requests
response = requests.get("http://172.22.188.51:8080/gopro/camera/setting?setting=3&option=5")
response.raise_for_status()
```
I got `403 Client Error`:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: http://172.22.188.51:8080/gopro/camera/setting?setting=3&option=5
```
All setting commands (provided in this table [https://gopro.github.io/OpenGoPro/http_2_0#settings-quick-reference](https://gopro.github.io/OpenGoPro/http_2_0#settings-quick-reference )) are encountering this issue.
However, when I try other HTTP commands, like `gopro/camera/state`, it looks fine.
```
import requests
response = requests.get("http://172.22.188.51:8080/gopro/camera/state")
response.raise_for_status()
print(response.json())

Output:
{'status': {'1': 0, '2': 0, '3': 0, '4': 255, '6': 0, '8': 0, '9': 0, '10': 0, '11': 0, '13': 0, '14': 0, '17': 0, '19': 0, '20': 0, '21': 0, '22': 0, '23': 0, '24': 0, '26': 0, '27': 0, '28': 0, '29': '', '30': 'GP25158288', '31': 0, '32': 0, '33': 0, '34': 0, '35': 8909, '36': 0, '37': 3, '38': 0, '39': 3, '41': 0, '42': 0, '45': 0, '49': 0, '54': 79142191, '55': 1, '56': 4, '58': 0, '59': 0, '60': 500, '61': 2, '62': 0, '63': 0, '64': 0, '65': 0, '66': 100, '67': 100, '68': 0, '69': 0, '70': 0, '74': 0, '75': 0, '76': 1, '77': 0, '78': 0, '81': 0, '82': 1, '83': 0, '85': 0, '86': 0, '88': 0, '89': 12, '90': 1, '91': 0, '93': 655360, '94': 786432, '95': 851968, '96': 1000, '97': 655360, '98': 17432576, '99': 2969, '100': 0, '101': 0, '102': 0, '103': 0, '105': 0, '106': 0, '107': 4294967295, '108': 0, '109': 0, '110': 0, '111': 0, '112': 0, '113': 0, '114': 0, '115': 0, '116': 1, '117': 124835840}, 'settings': {'2': 100, '3': 8, '5': 0, '6': 1, '13': 1, '19': 0, '24': 0, '30': 110, '31': 0, '32': 10, '37': 0, '41': 12, '42': 8, '43': 0, '44': 9, '45': 8, '47': 7, '54': 1, '59': 4, '62': 1200000, '64': 4, '75': 0, '76': 0, '83': 0, '84': 0, '85': 0, '86': 0, '87': 0, '88': 50, '91': 3, '102': 8, '103': 3, '105': 0, '111': 10, '112': 255, '114': 1, '115': 0, '116': 2, '117': 1, '118': 4, '121': 0, '122': 101, '123': 101, '124': 100, '125': 0, '126': 0, '128': 13, '129': 2, '130': 3, '131': 0, '132': 0, '134': 2, '135': 1, '139': 3, '144': 12, '145': 0, '146': 0, '147': 0, '148': 1, '149': 2, '150': 0, '151': 0, '153': 100, '154': 2, '155': 100, '156': 100, '157': 100, '158': 1, '159': 1, '160': 0, '161': 100, '162': 0, '163': 1, '164': 100, '167': 4, '168': 0, '169': 1, '174': 0, '175': 0, '176': 3, '177': 0, '178': 1, '179': 3, '180': 0, '181': 0}}
```

**Hardware**
- Camera: Hero11
- Desktop Linux

**Comment by GrayMask** [comment]
Oh, this problem is solved by rebooting GoPro...
I still no idea why `403 Client Error` occurred before.
