### ISSUE TITLE
Android tutorial app error

### ISSUE THREAD

**Issue by karolkadlubowski** [gopro/OpenGoPro#554]
**Component**
The bug is in the mobile tutorial app.

**Describe the bug**
When I launch the app, there is an error in command readCharacteristic invoked in perform().

**To Reproduce**
1. Launch app
2. Give permissions
3. Connect to gopro - now in logs there should be neverending Pairing communicate and after 30s there is timeout error.

E  kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 30000 ms
                                                                                                    	at kotlinx.coroutines.TimeoutKt.TimeoutCancellationException(Timeout.kt:184)
                                                                                                    	at kotlinx.coroutines.TimeoutCoroutine.run(Timeout.kt:154)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:883)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:100)
                                                                                                    	at android.os.Looper.loop(Looper.java:224)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7562)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Expected behavior**
There should be no errors.

**Hardware**
- Camera: Hero9 black
- Phone: Xiaomi Pocophone F1, Android 10 (but app was adjusted for older versions - error appearing before changed code invoked)

**Additional context**
Also other functions like checkStatus(receivedData.receive()) from Tutorial2SendBleCommands not working

**Comment by karolkadlubowski** [comment]
Probably I adjusted app incorrectly to previous android version, sorry for bothering
